name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ubuntu-docker-job:
    runs-on: ubuntu-latest
    name: "Ubuntu 22.10 Container"
    container:
      image: ubuntu:22.10
    steps:
      - uses: actions/checkout@v3
      - run: apt update && apt install --no-install-recommends -y lsb-release
      - run: cat /etc/lsb-release
